version: '3.8' 
 
 
services: 
  cassandra:
    image: cassandra:latest
    container_name: cassandra-container
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    volumes:
      - cassandra-data:/var/lib/cassandra

  redis:
    image: redis:latest
    hostname: redis-chat 
    container_name: redis-chat 
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
    environment:
      - REDIS_PORT=6379

volumes:
  cassandra-data:
  redis-data: