version: '3.8' 
 
networks: 
 
  cassandra: 
 
services: 
 
  cassandra1: 
 
    image: cassandra:latest 
 
    container_name: cassandra1 
 
    hostname: cassandra1 
 
    networks: 
 
      - cassandra 
 
    ports: 
 
      - "9042:9042" 
 
    environment: &environment  
 
        CASSANDRA_SEEDS: "cassandra1,cassandra2"   
 
        CASSANDRA_CLUSTER_NAME: MyTestCluster 
 
        CASSANDRA_DC: DC1 
 
        CASSANDRA_RACK: RACK1 
 
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch 
 
        CASSANDRA_NUM_TOKENS: 128 
    volumes:
      - cassandra-node-1:/var/lib/cassandra
    deploy:
      resources:
        limits:
          memory: 4G  # Adjust this based on your system's available memory
        reservations:
          memory: 1G  # Adjust this based on your container's requirements

  cassandra2: 
 
    image: cassandra:latest 
 
    container_name: cassandra2 
 
    hostname: cassandra2 
 
    networks: 
 
      - cassandra 
 
    ports: 
 
      - "9043:9042" 
 
    environment: *environment   
 
    depends_on: 
 
      cassandra1:  
 
        condition: service_started 
    volumes:
      - cassandra-node-2:/var/lib/cassandra
    deploy:
      resources:
        limits:
          memory: 4G  # Adjust this based on your system's available memory
        reservations:
          memory: 1G  # Adjust this based on your container's requirements


  cassandra3: 
 
    image: cassandra:latest 
 
    container_name: cassandra3 
 
    hostname: cassandra3 
 
    networks: 
 
      - cassandra 
 
    ports: 
 
      - "9044:9042" 
 
    environment: *environment   
 
    depends_on: 
      cassandra2:   
        condition: service_started
    volumes:
      - cassandra-node-3:/var/lib/cassandra
    deploy:
      resources:
        limits:
          memory: 4G  # Adjust this based on your system's available memory
        reservations:
          memory: 1G  # Adjust this based on your container's requirements
  redis:
    image: redis:latest
    hostname: redis-chat 
    container_name: redis-chat 
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/root/redis
    environment:
      - REDIS_PORT=6379

volumes:
  cassandra-node-1:
  cassandra-node-2:
  cassandra-node-3:
  redis-data: